name: Build

on: [push]

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci
      - run: npm test
      - run: npm run build

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: ./gradlew jar

      - name: Start Test DB
        run: docker-compose -p app up -d db && sleep 3 && docker-compose logs
      - name: Test Server
        run: ./gradlew --info test
      - name: E2E Tests
        run: ./gradlew --info -Pheadless=true e2eTest
      - name: Stop Test DB
        run: docker-compose -p app down

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test reports
          path: build/reports/tests

      - name: Build Docker image
        run: docker build -t $IMG:$GITHUB_SHA .
